// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg82dQXtzYAM7K82tTGFlCgBR92YWJkQo',
    appId: '1:282913737836:web:ee85139eb7ce056b521c49',
    messagingSenderId: '282913737836',
    projectId: 'kickplayer-d41dd',
    authDomain: 'kickplayer-d41dd.firebaseapp.com',
    storageBucket: 'kickplayer-d41dd.firebasestorage.app',
    measurementId: 'G-F4BLMZ507X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC01GTCu92FUhcvf4vRsWHbTSbIghKvZ1M',
    appId: '1:282913737836:android:585fbbf3c968bc8c521c49',
    messagingSenderId: '282913737836',
    projectId: 'kickplayer-d41dd',
    storageBucket: 'kickplayer-d41dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE7wytdWWIlixjhTdLhM38g5RufL_9GjU',
    appId: '1:282913737836:ios:ba51484f120aa6ba521c49',
    messagingSenderId: '282913737836',
    projectId: 'kickplayer-d41dd',
    storageBucket: 'kickplayer-d41dd.firebasestorage.app',
    iosBundleId: 'com.digital.Kaledal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE7wytdWWIlixjhTdLhM38g5RufL_9GjU',
    appId: '1:282913737836:ios:ba51484f120aa6ba521c49',
    messagingSenderId: '282913737836',
    projectId: 'kickplayer-d41dd',
    storageBucket: 'kickplayer-d41dd.firebasestorage.app',
    iosBundleId: 'com.digital.Kaledal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg82dQXtzYAM7K82tTGFlCgBR92YWJkQo',
    appId: '1:282913737836:web:647c36814e9946ae521c49',
    messagingSenderId: '282913737836',
    projectId: 'kickplayer-d41dd',
    authDomain: 'kickplayer-d41dd.firebaseapp.com',
    storageBucket: 'kickplayer-d41dd.firebasestorage.app',
    measurementId: 'G-LH29F092QY',
  );
}
